name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-widgets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: widgets
      - name: Build widgets
        run: npm run build
        working-directory: widgets
      - name: Deploy to Cloudflare Pages (Widgets)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: meteo24-widgets
          directory: widgets/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  deploy-viewer-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: viewer-app
      - name: Build viewer-app
        run: npm run build
        working-directory: viewer-app
      - name: Deploy to Cloudflare Pages (Viewer App)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: meteo24-viewer-app
          directory: viewer-app/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
